
import { DashboardConfig } from '@/types/dashboardConfig';

export const defaultConfig: DashboardConfig = {
  showConversion: true,
  showRevenue: true,
  showTicketFaturamento: false,
  showTicketReceita: false,
  showFaltaFaturamento: false,
  showFaltaReceita: false,
  showDiariaReceita: false,
  showDiariaFaturamento: false,
  showSuperMetaFaturamento: false,
  showSuperMetaReceita: false,
  showHiperMetaFaturamento: false,
  showHiperMetaReceita: false,
  showFaltaReceitaSuper: false,
  showFaltaReceitaHiper: false,
  showFaltaFaturamentoSuper: false,
  showFaltaFaturamentoHiper: false,
  showMetaFaturamento: false,
  showMetaReceita: false,
  showFaturamento: false,
  showReceita: false,
  showQuantidadeVendas: false,
  showCashCollect: false,
  showCac: false,
  showProjecaoReceita: false,
  showProjecaoFaturamento: false,
  showNoShow: false,
  showClosersPerformanceTable: true,
  showPreSalesCalls: true,
  showPreSalesSchedulings: true,
  showPreSalesNoShow: true,
  showPreSalesSDRTable: true,
  showPreSalesCallsChart: true,
  showPreSalesSchedulingChart: true,
  showPreSalesNoShowChart: true,
  showPreSalesSDRComparisonChart: true,
  companyName: '',
  metricsOrder: [
    'showConversion', 'showRevenue', 'showTicketFaturamento', 'showTicketReceita',
    'showFaltaFaturamento', 'showFaltaReceita', 'showDiariaReceita', 'showDiariaFaturamento',
    'showSuperMetaFaturamento', 'showSuperMetaReceita', 'showHiperMetaFaturamento', 'showHiperMetaReceita',
    'showFaltaReceitaSuper', 'showFaltaReceitaHiper', 'showFaltaFaturamentoSuper', 'showFaltaFaturamentoHiper',
    'showMetaFaturamento', 'showMetaReceita', 'showFaturamento', 'showReceita',
    'showQuantidadeVendas', 'showCashCollect', 'showCac',
    'showProjecaoReceita', 'showProjecaoFaturamento', 'showNoShow'
  ],
  preSalesOrder: [
    'showPreSalesCalls',
    'showPreSalesSchedulings', 
    'showPreSalesNoShow'
  ],
  productOrder: [
    'showProductReceita',
    'showProductFaturamento',
    'showProductQuantidadeVendas',
    'showProductTicketReceita',
    'showProductTicketFaturamento',
    'showProductMetaReceita',
    'showProductMetaFaturamento',
    'showProductMetaQuantidadeVendas',
    'showProductFaltaReceita',
    'showProductFaltaFaturamento',
    'showProductCashCollect',
    'showProductProjecaoReceita',
    'showProductProjecaoFaturamento'
  ],
  showSpecificGoals: false,
  selectedGoalIds: [],
  showRevenueEvolutionChart: true,
  showBillingEvolutionChart: true,
  showSellerRevenueChart: true,
  showSellerBillingChart: true,
  showTemporalRevenueChart: true,
  showTemporalBillingChart: true,
  
  // Product metrics defaults
  showProductMetrics: false,
  selectedProductIds: [],
  showProductTicketReceita: false,
  showProductFaturamento: false,
  showProductReceita: false,
  showProductQuantidadeVendas: false,
  showProductMetaFaturamento: false,
  showProductMetaReceita: false,
  showProductMetaQuantidadeVendas: false,
  showProductTicketFaturamento: false,
  showProductFaltaFaturamento: false,
  showProductFaltaReceita: false,
  showProductCashCollect: false,
  showProductProjecaoReceita: false,
  showProductProjecaoFaturamento: false,
};
