
import { DashboardConfig } from '@/types/dashboardConfig';

export const defaultConfig: DashboardConfig = {
  showConversion: false,
  showRevenue: true,
  showTicketFaturamento: false,
  showTicketReceita: false,
  showFaltaFaturamento: false,
  showFaltaReceita: false,
  showDiariaReceita: false,
  showDiariaFaturamento: false,
  showSuperMetaFaturamento: false,
  showSuperMetaReceita: false,
  showHiperMetaFaturamento: false,
  showHiperMetaReceita: false,
  showFaltaReceitaSuper: false,
  showFaltaReceitaHiper: false,
  showFaltaFaturamentoSuper: false,
  showFaltaFaturamentoHiper: false,
  showMetaFaturamento: false,
  showMetaReceita: false,
  showFaturamento: false,
  showReceita: false,
  showQuantidadeVendas: false,
  showCashCollect: false,
  showCac: false,
  showProjecaoReceita: false,
  showProjecaoFaturamento: false,
  showNoShow: false,
  showClosersPerformanceTable: false,
  showPreSalesCalls: true,
  showPreSalesSchedulings: true,
  showPreSalesNoShow: true,
  showPreSalesSDRTable: true,
  showPreSalesCallsChart: true,
  showPreSalesSchedulingChart: true,
  showPreSalesNoShowChart: true,
  showPreSalesSDRComparisonChart: true,
  companyName: 'Sua Empresa',
  metricsOrder: [
    'showMetaFaturamento',
    'showFaturamento',
    'showTicketFaturamento',
    'showDiariaFaturamento',
    'showFaltaFaturamento',
    'showProjecaoFaturamento',
    'showMetaReceita',
    'showRevenue',
    'showReceita',
    'showTicketReceita',
    'showFaltaReceita',
    'showDiariaReceita',
    'showProjecaoReceita',
    'showQuantidadeVendas',
    'showConversion',
    'showCashCollect',
    'specificGoals',
    'showCac',
    'showNoShow',
    'showClosersPerformanceTable',
    'revenueEvolutionChart',
    'billingEvolutionChart',
    'sellerRevenueChart',
    'sellerBillingChart',
    'temporalRevenueChart',
    'temporalBillingChart'
  ],
  preSalesOrder: [
    'showPreSalesCalls',
    'showPreSalesSchedulings',
    'showPreSalesNoShow',
    'showPreSalesSDRTable',
    'showPreSalesSDRComparisonChart',
    'showPreSalesCallsChart',
    'showPreSalesSchedulingChart',
    'showPreSalesNoShowChart'
  ],
  productOrder: [
    'showProductMetaFaturamento',
    'showProductFaturamento',
    'showProductFaltaFaturamento',
    'showProductProjecaoFaturamento',
    'showProductTicketFaturamento',
    'showProductMetaReceita',
    'showProductReceita',
    'showProductFaltaReceita',
    'showProductTicketReceita',
    'showProductProjecaoReceita',
    'showProductCashCollect',
    'showProductMetaQuantidadeVendas',
    'showProductQuantidadeVendas'
  ],
  showSpecificGoals: true, // ✅ Habilitado por padrão
  selectedGoalIds: [],
  showRevenueEvolutionChart: false,
  showBillingEvolutionChart: false,
  showSellerRevenueChart: false,
  showSellerBillingChart: false,
  showTemporalRevenueChart: false,
  showTemporalBillingChart: false,
  showProductMetrics: false,
  selectedProductIds: [],
  showProductTicketReceita: false,
  showProductTicketFaturamento: false,
  showProductFaturamento: false,
  showProductReceita: false,
  showProductQuantidadeVendas: false,
  showProductMetaFaturamento: false,
  showProductMetaReceita: false,
  showProductMetaQuantidadeVendas: false,
  showProductFaltaFaturamento: false,
  showProductFaltaReceita: false,
  showProductCashCollect: false,
  showProductProjecaoReceita: false,
  showProductProjecaoFaturamento: false,
  showProductRevenueEvolutionChart: false,
  showProductBillingEvolutionChart: false,
  showProductSalesEvolutionChart: false,
  showProductPerformanceChart: false,
  showProductComparisonChart: false,
  showProductTemporalChart: false,
};

