
import { DashboardConfig } from '@/types/dashboardConfig';

export const defaultConfig: DashboardConfig = {
  showConversion: true,
  showRevenue: true,
  showTicketFaturamento: true,
  showTicketReceita: true,
  showFaltaFaturamento: true,
  showFaltaReceita: true,
  showDiariaReceita: true,
  showDiariaFaturamento: true,
  showSuperMetaFaturamento: true,
  showSuperMetaReceita: true,
  showHiperMetaFaturamento: true,
  showHiperMetaReceita: true,
  showFaltaReceitaSuper: true,
  showFaltaReceitaHiper: true,
  showFaltaFaturamentoSuper: true,
  showFaltaFaturamentoHiper: true,
  showMetaFaturamento: true,
  showMetaReceita: true,
  showFaturamento: true,
  showReceita: true,
  showQuantidadeVendas: true,
  showCashCollect: true,
  showCac: true,
  showProjecaoReceita: true,
  showProjecaoFaturamento: true,
  showNoShow: true,
  showClosersPerformanceTable: true,
  showPreSalesCalls: true,
  showPreSalesSchedulings: true,
  showPreSalesNoShow: true,
  showPreSalesSDRTable: true,
  showPreSalesCallsChart: true,
  showPreSalesSchedulingChart: true,
  showPreSalesNoShowChart: true,
  showPreSalesSDRComparisonChart: true,
  companyName: 'Minha Empresa',
  metricsOrder: [
    'showConversion', 'showRevenue', 'showTicketFaturamento', 'showTicketReceita',
    'showFaltaFaturamento', 'showFaltaReceita', 'showDiariaReceita', 'showDiariaFaturamento',
    'showSuperMetaFaturamento', 'showSuperMetaReceita', 'showHiperMetaFaturamento', 'showHiperMetaReceita',
    'showFaltaReceitaSuper', 'showFaltaReceitaHiper', 'showFaltaFaturamentoSuper', 'showFaltaFaturamentoHiper',
    'showMetaFaturamento', 'showMetaReceita', 'showFaturamento', 'showReceita',
    'showQuantidadeVendas', 'showCashCollect', 'showCac',
    'showProjecaoReceita', 'showProjecaoFaturamento', 'showNoShow'
  ],
  preSalesOrder: [
    'showPreSalesCalls', 'showPreSalesSchedulings', 'showPreSalesNoShow', 'showPreSalesSDRTable',
    'showPreSalesCallsChart', 'showPreSalesSchedulingChart', 'showPreSalesNoShowChart', 'showPreSalesSDRComparisonChart'
  ],
  productOrder: [
    'showProductReceita', 'showProductFaturamento', 'showProductQuantidadeVendas',
    'showProductTicketReceita', 'showProductTicketFaturamento',
    'showProductMetaReceita', 'showProductMetaFaturamento', 'showProductMetaQuantidadeVendas',
    'showProductFaltaReceita', 'showProductFaltaFaturamento',
    'showProductCashCollect', 'showProductProjecaoReceita', 'showProductProjecaoFaturamento',
    'showProductRevenueEvolutionChart', 'showProductBillingEvolutionChart',
    'showSellerRevenueChart', 'showSellerBillingChart', 
    'showTemporalRevenueChart', 'showTemporalBillingChart'
  ],
  showRevenueEvolutionChart: true,
  showBillingEvolutionChart: true,
  showSellerRevenueChart: true,
  showSellerBillingChart: true,
  showTemporalRevenueChart: true,
  showTemporalBillingChart: true,
  
  // Product metrics fields
  showProductMetrics: true,
  selectedProductIds: [],
  showProductTicketReceita: true,
  showProductTicketFaturamento: true,
  showProductFaturamento: true,
  showProductReceita: true,
  showProductQuantidadeVendas: true,
  showProductMetaFaturamento: true,
  showProductMetaReceita: true,
  showProductMetaQuantidadeVendas: true,
  showProductFaltaFaturamento: true,
  showProductFaltaReceita: true,
  showProductCashCollect: true,
  showProductProjecaoReceita: true,
  showProductProjecaoFaturamento: true,

  // Product charts fields - apenas os dois que ficaram
  showProductRevenueEvolutionChart: true,
  showProductBillingEvolutionChart: true,

  // CONFIGURAÇÕES DE CONTROLE DE ABAS
  enableCommercialTab: true,
  enableProductTab: true,
  enablePreSalesTab: true,
};
