import { DashboardConfig } from '@/types/dashboardConfig';

export const mapConfigToDatabase = (config: DashboardConfig) => {
  return {
    metrics_order: config.metricsOrder,
    pre_sales_order: config.preSalesOrder,
    product_order: config.productOrder,
    show_conversion: config.showConversion,
    show_revenue: config.showRevenue,
    show_ticket_faturamento: config.showTicketFaturamento,
    show_ticket_receita: config.showTicketReceita,
    show_falta_faturamento: config.showFaltaFaturamento,
    show_falta_receita: config.showFaltaReceita,
    show_diaria_receita: config.showDiariaReceita,
    show_diaria_faturamento: config.showDiariaFaturamento,
    show_super_meta_faturamento: config.showSuperMetaFaturamento,
    show_super_meta_receita: config.showSuperMetaReceita,
    show_hiper_meta_faturamento: config.showHiperMetaFaturamento,
    show_hiper_meta_receita: config.showHiperMetaReceita,
    show_falta_receita_super: config.showFaltaReceitaSuper,
    show_falta_receita_hiper: config.showFaltaReceitaHiper,
    show_falta_faturamento_super: config.showFaltaFaturamentoSuper,
    show_falta_faturamento_hiper: config.showFaltaFaturamentoHiper,
    show_meta_faturamento: config.showMetaFaturamento,
    show_meta_receita: config.showMetaReceita,
    show_faturamento: config.showFaturamento,
    show_receita: config.showReceita,
    show_quantidade_vendas: config.showQuantidadeVendas,
    show_cash_collect: config.showCashCollect,
    show_cac: config.showCac,
    show_projecao_receita: config.showProjecaoReceita,
    show_projecao_faturamento: config.showProjecaoFaturamento,
    show_no_show: config.showNoShow,
    show_closers_performance_table: config.showClosersPerformanceTable,
    show_pre_sales_calls: config.showPreSalesCalls,
    show_pre_sales_schedulings: config.showPreSalesSchedulings,
    show_pre_sales_no_show: config.showPreSalesNoShow,
    show_pre_sales_sdr_table: config.showPreSalesSDRTable,
    show_pre_sales_calls_chart: config.showPreSalesCallsChart,
    show_pre_sales_scheduling_chart: config.showPreSalesSchedulingChart,
    show_pre_sales_no_show_chart: config.showPreSalesNoShowChart,
    show_pre_sales_sdr_comparison_chart: config.showPreSalesSDRComparisonChart,
    company_name: config.companyName,
    show_revenue_evolution_chart: config.showRevenueEvolutionChart,
    show_billing_evolution_chart: config.showBillingEvolutionChart,
    show_seller_revenue_chart: config.showSellerRevenueChart,
    show_seller_billing_chart: config.showSellerBillingChart,
    show_temporal_revenue_chart: config.showTemporalRevenueChart,
    show_temporal_billing_chart: config.showTemporalBillingChart,
    show_product_metrics: config.showProductMetrics,
    selected_product_ids: config.selectedProductIds,
    show_product_ticket_receita: config.showProductTicketReceita,
    show_product_ticket_faturamento: config.showProductTicketFaturamento,
    show_product_faturamento: config.showProductFaturamento,
    show_product_receita: config.showProductReceita,
    show_product_quantidade_vendas: config.showProductQuantidadeVendas,
    show_product_meta_faturamento: config.showProductMetaFaturamento,
    show_product_meta_receita: config.showProductMetaReceita,
    show_product_meta_quantidade_vendas: config.showProductMetaQuantidadeVendas,
    show_product_falta_faturamento: config.showProductFaltaFaturamento,
    show_product_falta_receita: config.showProductFaltaReceita,
    show_product_cash_collect: config.showProductCashCollect,
    show_product_projecao_receita: config.showProductProjecaoReceita,
    show_product_projecao_faturamento: config.showProductProjecaoFaturamento,
    
    // Product charts mappings - apenas os dois que ficaram
    show_product_revenue_evolution_chart: config.showProductRevenueEvolutionChart,
    show_product_billing_evolution_chart: config.showProductBillingEvolutionChart,

    // MAPEAMENTOS DE CONTROLE DE ABAS
    enable_commercial_tab: config.enableCommercialTab,
    enable_product_tab: config.enableProductTab,
    enable_pre_sales_tab: config.enablePreSalesTab,
  };
};

export const mapDatabaseToConfig = (data: any): DashboardConfig => {
  return {
    showConversion: data.show_conversion ?? true,
    showRevenue: data.show_revenue ?? true,
    showTicketFaturamento: data.show_ticket_faturamento ?? true,
    showTicketReceita: data.show_ticket_receita ?? true,
    showFaltaFaturamento: data.show_falta_faturamento ?? true,
    showFaltaReceita: data.show_falta_receita ?? true,
    showDiariaReceita: data.show_diaria_receita ?? true,
    showDiariaFaturamento: data.show_diaria_faturamento ?? true,
    showSuperMetaFaturamento: data.show_super_meta_faturamento ?? true,
    showSuperMetaReceita: data.show_super_meta_receita ?? true,
    showHiperMetaFaturamento: data.show_hiper_meta_faturamento ?? true,
    showHiperMetaReceita: data.show_hiper_meta_receita ?? true,
    showFaltaReceitaSuper: data.show_falta_receita_super ?? true,
    showFaltaReceitaHiper: data.show_falta_receita_hiper ?? true,
    showFaltaFaturamentoSuper: data.show_falta_faturamento_super ?? true,
    showFaltaFaturamentoHiper: data.show_falta_faturamento_hiper ?? true,
    showMetaFaturamento: data.show_meta_faturamento ?? true,
    showMetaReceita: data.show_meta_receita ?? true,
    showFaturamento: data.show_faturamento ?? true,
    showReceita: data.show_receita ?? true,
    showQuantidadeVendas: data.show_quantidade_vendas ?? true,
    showCashCollect: data.show_cash_collect ?? true,
    showCac: data.show_cac ?? true,
    showProjecaoReceita: data.show_projecao_receita ?? true,
    showProjecaoFaturamento: data.show_projecao_faturamento ?? true,
    showNoShow: data.show_no_show ?? true,
    showClosersPerformanceTable: data.show_closers_performance_table ?? true,
    showPreSalesCalls: data.show_pre_sales_calls ?? true,
    showPreSalesSchedulings: data.show_pre_sales_schedulings ?? true,
    showPreSalesNoShow: data.show_pre_sales_no_show ?? true,
    showPreSalesSDRTable: data.show_pre_sales_sdr_table ?? true,
    showPreSalesCallsChart: data.show_pre_sales_calls_chart ?? true,
    showPreSalesSchedulingChart: data.show_pre_sales_scheduling_chart ?? true,
    showPreSalesNoShowChart: data.show_pre_sales_no_show_chart ?? true,
    showPreSalesSDRComparisonChart: data.show_pre_sales_sdr_comparison_chart ?? true,
    companyName: data.company_name || 'Minha Empresa',
    metricsOrder: data.metrics_order || [],
    preSalesOrder: data.pre_sales_order || [],
    productOrder: data.product_order || [],
    showRevenueEvolutionChart: data.show_revenue_evolution_chart ?? true,
    showBillingEvolutionChart: data.show_billing_evolution_chart ?? true,
    showSellerRevenueChart: data.show_seller_revenue_chart ?? true,
    showSellerBillingChart: data.show_seller_billing_chart ?? true,
    showTemporalRevenueChart: data.show_temporal_revenue_chart ?? true,
    showTemporalBillingChart: data.show_temporal_billing_chart ?? true,
    showProductMetrics: data.show_product_metrics ?? true,
    selectedProductIds: data.selected_product_ids || [],
    showProductTicketReceita: data.show_product_ticket_receita ?? true,
    showProductTicketFaturamento: data.show_product_ticket_faturamento ?? true,
    showProductFaturamento: data.show_product_faturamento ?? true,
    showProductReceita: data.show_product_receita ?? true,
    showProductQuantidadeVendas: data.show_product_quantidade_vendas ?? true,
    showProductMetaFaturamento: data.show_product_meta_faturamento ?? true,
    showProductMetaReceita: data.show_product_meta_receita ?? true,
    showProductMetaQuantidadeVendas: data.show_product_meta_quantidade_vendas ?? true,
    showProductFaltaFaturamento: data.show_product_falta_faturamento ?? true,
    showProductFaltaReceita: data.show_product_falta_receita ?? true,
    showProductCashCollect: data.show_product_cash_collect ?? true,
    showProductProjecaoReceita: data.show_product_projecao_receita ?? true,
    showProductProjecaoFaturamento: data.show_product_projecao_faturamento ?? true,
    
    // Product charts fields - apenas os dois que ficaram
    showProductRevenueEvolutionChart: data.show_product_revenue_evolution_chart ?? true,
    showProductBillingEvolutionChart: data.show_product_billing_evolution_chart ?? true,

    // CAMPOS DE CONTROLE DE ABAS
    enableCommercialTab: data.enable_commercial_tab ?? true,
    enableProductTab: data.enable_product_tab ?? true,
    enablePreSalesTab: data.enable_pre_sales_tab ?? true,
  };
};
