
// Base expandida de ações específicas por categoria com títulos imperativos
export const comprehensiveActionTemplates = {
  comercial: [
    'Revise e otimize o ICP (Ideal Customer Profile)',
    'Mapeie a jornada de compra do cliente completa',
    'Desenvolva novos canais de aquisição de leads',
    'Crie um funil de vendas baseado em conteúdo (Inbound Sales)',
    'Implemente um funil de vendas de alta conversão',
    'Defina e monitore taxas de conversão em cada etapa do funil',
    'Realize prospecção ativa (Outbound Sales) otimizada',
    'Personalize abordagens de vendas para cada segmento',
    'Crie roteiros de vendas flexíveis (Playbooks)',
    'Ofereça treinamento contínuo em negociação e fechamento',
    'Desenvolva programas de incentivo para a equipe de vendas',
    'Implemente processo de qualificação de leads rigoroso (BANT, SPIN)',
    'Utilize provas sociais e cases de sucesso nas propostas',
    'Crie pacotes de serviços otimizados para diferentes segmentos',
    'Realize análise de perda de oportunidades (Lost Deals Analysis)',
    'Promova colaboração entre Marketing e Vendas (Smarketing)',
    'Explore vendas consultivas e posicionamento como solucionador',
    'Desenvolva programas de parceria para revendedores/afiliados',
    'Realize eventos de prospecção (Workshops, Feiras Virtuais)',
    'Monitore o ciclo de vendas e busque reduzi-lo',
    'Implemente CRM (Customer Relationship Management) avançado',
    'Ofereça testes gratuitos ou demonstrações de produto/serviço',
    'Treine a equipe de vendas em técnicas de fechamento',
    'Crie urgência e escassez em ofertas (com ética)',
    'Personalize a comunicação com o cliente',
    'Utilize ferramentas de automação de vendas',
    'Realize pesquisas de mercado para novas ofertas',
    'Desenvolva landing pages otimizadas para conversão',
    'Analise as métricas de vendas regularmente',
    'Implemente sistema de follow-up automático',
    'Estruture processo de vendas B2B consultivas',
    'Defina território de vendas por representante',
    'Estabeleça metas de vendas SMART por período',
    'Crie scripts de objeções mais comuns',
    'Implemente sistema de comissões motivador',
    'Desenvolva estratégia de vendas por telefone',
    'Monte equipe de pré-vendas especializada',
    'Crie processo de vendas para clientes recorrentes',
    'Estabeleça parcerias com distribuidores',
    'Implemente vendas cruzadas (cross-selling)',
    'Desenvolva estratégia de vendas diretas',
    'Crie sistema de referral para clientes',
    'Estabeleça processo de reativação de leads frios',
    'Implemente técnicas de social selling',
    'Desenvolva estratégia de vendas por região',
    'Crie sistema de qualificação por scoring',
    'Estabeleça processo de negociação estruturado',
    'Implemente vendas por assinatura/recorrência',
    'Desenvolva estratégia de vendas online',
    'Crie processo de vendas para grandes contas',
    'Estabeleça sistema de previsão de vendas',
    'Implemente estratégia de vendas omnichannel',
    'Desenvolva programa de capacitação em vendas',
    'Crie sistema de análise de concorrentes',
    'Estabeleça processo de qualificação MEDDIC',
    'Implemente estratégia de Account Based Sales',
    'Desenvolva metodologia de vendas própria',
    'Crie sistema de gestão de pipeline robusto',
    'Estabeleça processo de vendas consultivas',
    'Implemente estratégia de vendas complexas',
    'Desenvolva programa de mentoring em vendas'
  ],
  marketing: [
    'Otimize o Site/Loja Online (SEO completo)',
    'Invista em Marketing de Conteúdo estratégico',
    'Utilize Mídias Sociais de forma estratégica',
    'Desenvolva campanhas de E-mail Marketing segmentadas',
    'Implemente anúncios pagos (Google Ads, Meta Ads)',
    'Crie parcerias estratégicas (Co-marketing)',
    'Otimize o funil de conversão digital',
    'Ofereça webinars ou workshops gratuitos',
    'Solicite e publique depoimentos de clientes',
    'Participe de eventos do setor para networking',
    'Desenvolva programas de indicação de clientes',
    'Implemente automação de marketing avançada',
    'Realize auditoria completa de marketing digital',
    'Aprimore estratégia de SEO On-page e Off-page',
    'Invista em publicidade programática e retargeting',
    'Desenvolva estratégia de conteúdo multicanal',
    'Explore marketing de influência setorial',
    'Otimize marketing de vídeo (YouTube, Reels, TikTok)',
    'Personalize experiência do usuário no site',
    'Utilize LinkedIn estrategicamente para leads B2B',
    'Invista em marketing de eventos online',
    'Desenvolva estratégia de PR digital',
    'Crie conteúdo interativo (quizzes, calculadoras)',
    'Aproveite potencial do WhatsApp Business',
    'Faça testes A/B consistentes em landing pages',
    'Monitore reputação online (brand monitoring)',
    'Desenvolva estratégia de podcast',
    'Utilize ferramentas de análise de dados',
    'Crie campanhas de e-mail para clientes inativos',
    'Invista em CRO (Conversion Rate Optimization)',
    'Implemente estratégia de Inbound Marketing',
    'Desenvolva personas de clientes detalhadas',
    'Crie calendário editorial para redes sociais',
    'Estabeleça estratégia de marketing mobile',
    'Implemente marketing automation workflows',
    'Desenvolva estratégia de content marketing',
    'Crie programa de marketing de afiliados',
    'Estabeleça estratégia de remarketing',
    'Implemente Google Analytics 4 corretamente',
    'Desenvolva estratégia de vídeo marketing',
    'Crie campanhas de nurturing de leads',
    'Estabeleça estratégia de social media',
    'Implemente pixel de conversão otimizado',
    'Desenvolva estratégia de growth hacking',
    'Crie sistema de lead scoring avançado',
    'Estabeleça estratégia de marketing local',
    'Implemente chatbots para geração de leads',
    'Desenvolva estratégia de marketing viral',
    'Crie programa de embaixadores da marca',
    'Estabeleça estratégia de marketing sazonais',
    'Implemente ferramentas de marketing analytics',
    'Desenvolva estratégia de marketing direto',
    'Crie campanhas de upsell e cross-sell',
    'Estabeleça estratégia de marketing educacional',
    'Implemente marketing baseado em dados',
    'Desenvolva estratégia de marketing experiencial',
    'Crie programa de retenção de clientes',
    'Estabeleça estratégia de marketing de relacionamento',
    'Implemente marketing omnichannel integrado',
    'Desenvolva estratégia de marketing conversacional',
    'Crie sistema de attribution modeling',
    'Estabeleça estratégia de marketing preditivo',
    'Implemente ferramentas de competitor analysis',
    'Desenvolva estratégia de voice search optimization',
    'Crie programa de customer advocacy',
    'Estabeleça estratégia de marketing automation',
    'Implemente ferramentas de heat mapping',
    'Desenvolva estratégia de interactive marketing',
    'Crie sistema de real-time personalization',
    'Estabeleça estratégia de micro-moments marketing'
  ],
  gestao: [
    'Revise Missão, Visão e Valores da empresa',
    'Defina ou reafirme nicho de mercado específico',
    'Analise concorrência (Benchmarking detalhado)',
    'Realize análise SWOT completa',
    'Estabeleça metas SMART para todas as áreas',
    'Desenvolva plano de negócios flexível',
    'Crie cronograma de revisão estratégica',
    'Identifique e priorize maiores oportunidades de crescimento',
    'Mapeie cenário econômico e político',
    'Defina indicadores chave de performance (KPIs)',
    'Documente todos os processos comerciais',
    'Automatize tarefas repetitivas no CRM',
    'Implemente sistema de gestão de contratos eletrônico',
    'Crie dashboard de performance comercial',
    'Revise e otimize ciclo de pagamento',
    'Centralize informações de clientes em CRM único',
    'Desenvolva fluxo de aprovação de propostas claro',
    'Defina SLAs para processos internos e externos',
    'Realize auditorias internas de processos',
    'Simplifique processo de cotação e orçamento',
    'Implemente sistema de feedback interno contínuo',
    'Otimize gestão do tempo da equipe',
    'Realize reuniões de alinhamento regulares',
    'Utilize metodologias de gestão de projetos',
    'Revise estrutura organizacional',
    'Implemente sistema de gestão do conhecimento',
    'Crie cultura de melhoria contínua',
    'Estabeleça processo de tomada de decisão',
    'Implemente gestão por resultados',
    'Desenvolva planejamento estratégico anual',
    'Crie sistema de gestão de riscos empresariais',
    'Estabeleça governança corporativa adequada',
    'Implemente balanced scorecard organizacional',
    'Desenvolva estratégia de inovação empresarial',
    'Crie sistema de gestão de stakeholders',
    'Estabeleça processo de sucessão executiva',
    'Implemente gestão ágil de projetos',
    'Desenvolva estratégia de transformação digital',
    'Crie sistema de inteligência competitiva',
    'Estabeleça processo de gestão de mudanças',
    'Implemente sistema de gestão ambiental',
    'Desenvolva estratégia de responsabilidade social',
    'Crie programa de compliance corporativo',
    'Estabeleça sistema de auditoria interna',
    'Implemente gestão de crise estruturada',
    'Desenvolva estratégia de internacionalização',
    'Crie sistema de gestão de qualidade total',
    'Estabeleça processo de due diligence',
    'Implemente sistema de business intelligence',
    'Desenvolva estratégia de fusões e aquisições',
    'Crie programa de lean management',
    'Estabeleça sistema de gestão de contratos',
    'Implemente metodologia six sigma',
    'Desenvolva estratégia de diversificação',
    'Crie sistema de gestão de fornecedores',
    'Estabeleça processo de benchmarking contínuo',
    'Implemente sistema de gestão de projetos PMO',
    'Desenvolva estratégia de economia circular',
    'Crie programa de gestão de talentos',
    'Estabeleça sistema de gestão de performance',
    'Implemente metodologia OKRs organizacional',
    'Desenvolva estratégia de customer centricity',
    'Crie sistema de gestão de dados (data governance)',
    'Estabeleça processo de planejamento cenários',
    'Implemente sistema de gestão de crises',
    'Desenvolva estratégia de sustentabilidade corporativa',
    'Crie programa de excelência operacional',
    'Estabeleça sistema de gestão de reputação',
    'Implemente metodologia design thinking',
    'Desenvolva estratégia de transformação cultural'
  ],
  financeiro: [
    'Faça planejamento financeiro detalhado',
    'Controle rigorosamente o fluxo de caixa',
    'Busque fontes de financiamento estratégicas',
    'Negocie com fornecedores para reduzir custos',
    'Otimize gestão de estoques',
    'Monitore custos fixos e variáveis',
    'Realize análise de viabilidade econômica para projetos',
    'Revise estrutura de preços regularmente',
    'Digitalize processos financeiros',
    'Busque assessoria contábil e financeira especializada',
    'Gerencie recebíveis e inadimplência',
    'Defina ponto de equilíbrio operacional',
    'Considere otimização fiscal',
    'Monitore margem de lucro',
    'Crie reservas de emergência',
    'Implemente controles internos robustos',
    'Automatize conciliação bancária',
    'Crie relatórios financeiros gerenciais',
    'Estabeleça orçamento por centro de custo',
    'Implemente análise de ROI por projeto',
    'Desenvolva modelo de precificação dinâmica',
    'Crie sistema de cobrança eficiente',
    'Implemente controle de despesas rigoroso',
    'Estabeleça política de crédito clara',
    'Monitore indicadores financeiros diariamente',
    'Crie projeções financeiras realistas',
    'Implemente gestão de risco financeiro',
    'Estabeleça metas financeiras por período',
    'Crie dashboard financeiro executivo',
    'Implemente auditoria financeira interna',
    'Desenvolva análise de sensibilidade financeira',
    'Crie sistema de planejamento tributário',
    'Estabeleça controle de capital de giro',
    'Implemente gestão de tesouraria avançada',
    'Desenvolva análise de break-even por produto',
    'Crie sistema de controle de custos ABC',
    'Estabeleça análise de rentabilidade por cliente',
    'Implemente sistema de budgeting rolling',
    'Desenvolva análise de valor econômico agregado',
    'Crie sistema de hedge para riscos cambiais',
    'Estabeleça controle de margem de contribuição',
    'Implemente análise de alavancagem financeira',
    'Desenvolva sistema de credit scoring interno',
    'Crie análise de ciclo de conversão de caixa',
    'Estabeleça controle de working capital',
    'Implemente sistema de factoring estratégico',
    'Desenvolva análise de custo de capital',
    'Crie sistema de avaliação de investimentos',
    'Estabeleça controle de EBITDA por unidade',
    'Implemente análise de economic value added',
    'Desenvolva sistema de pricing baseado em valor',
    'Crie controle de debt-to-equity ratio',
    'Estabeleça análise de cash flow descontado',
    'Implemente sistema de financial forecasting',
    'Desenvolva análise de return on assets',
    'Crie sistema de variance analysis mensal',
    'Estabeleça controle de liquidity ratios',
    'Implemente análise de profitability ratios',
    'Desenvolva sistema de cost accounting avançado',
    'Crie controle de activity-based costing',
    'Estabeleça análise de capital allocation',
    'Implemente sistema de performance budgeting',
    'Desenvolva análise de financial leverage',
    'Crie sistema de cash management otimizado',
    'Estabeleça controle de inventory turnover',
    'Implemente análise de asset utilization',
    'Desenvolva sistema de zero-based budgeting',
    'Crie controle de debt service coverage',
    'Estabeleça análise de working capital efficiency',
    'Implemente sistema de financial modeling avançado'
  ],
  rh: [
    'Contrate talentos alinhados à cultura da empresa',
    'Invista em treinamento e desenvolvimento da equipe',
    'Delegue tarefas de forma eficaz',
    'Fomente ambiente de trabalho positivo e colaborativo',
    'Implemente sistema de reconhecimento e recompensas',
    'Estabeleça metas claras e feedback regular',
    'Promova comunicação transparente e aberta',
    'Incentive proatividade e inovação na equipe',
    'Desenvolva líderes internos',
    'Realize pesquisas de clima organizacional',
    'Ofereça flexibilidade no trabalho',
    'Promova saúde mental e bem-estar dos colaboradores',
    'Crie plano de carreira para colaboradores chave',
    'Promova diversidade e inclusão',
    'Celebre conquistas da equipe',
    'Implemente processo de recrutamento estruturado',
    'Crie programa de integração (onboarding)',
    'Estabeleça política de remuneração competitiva',
    'Desenvolva programa de sucessão',
    'Implemente avaliação de desempenho 360°',
    'Crie programa de mentoria interna',
    'Estabeleça código de conduta empresarial',
    'Implemente gestão de talentos',
    'Crie política de desenvolvimento pessoal',
    'Estabeleça programa de benefícios atrativo',
    'Implemente gestão por competências',
    'Crie cultura de feedback contínuo',
    'Estabeleça programa de retenção de talentos',
    'Implemente sistema de gestão de performance',
    'Crie programa de capacitação contínua',
    'Desenvolva programa de employee branding',
    'Estabeleça sistema de talent pipeline',
    'Implemente programa de high potentials',
    'Crie sistema de job rotation estruturado',
    'Desenvolva programa de cross-training',
    'Estabeleça sistema de internal mobility',
    'Implemente programa de leadership development',
    'Crie sistema de performance coaching',
    'Desenvolva programa de employee engagement',
    'Estabeleça sistema de competency mapping',
    'Implemente programa de work-life balance',
    'Crie sistema de talent retention strategies',
    'Desenvolva programa de organizational culture',
    'Estabeleça sistema de employee value proposition',
    'Implemente programa de change management',
    'Crie sistema de knowledge management',
    'Desenvolva programa de team building',
    'Estabeleça sistema de conflict resolution',
    'Implemente programa de employee wellness',
    'Crie sistema de performance management',
    'Desenvolva programa de career development',
    'Estabeleça sistema de succession planning',
    'Implemente programa de talent acquisition',
    'Crie sistema de employer branding',
    'Desenvolva programa de learning and development',
    'Estabeleça sistema de compensation and benefits',
    'Implemente programa de diversity and inclusion',
    'Crie sistema de employee relations',
    'Desenvolva programa de organizational development',
    'Estabeleça sistema de human capital analytics',
    'Implemente programa de workforce planning',
    'Crie sistema de employee experience design',
    'Desenvolva programa de culture transformation',
    'Estabeleça sistema de talent management platform',
    'Implemente programa de remote work policies',
    'Crie sistema de performance dashboard',
    'Desenvolva programa de employee advocacy',
    'Estabeleça sistema de exit interview insights',
    'Implemente programa de generation gap management',
    'Crie sistema de skills gap analysis'
  ],
  operacional: [
    'Mapeie e otimize processos internos',
    'Digitalize e automatize tarefas repetitivas',
    'Implemente sistema de gestão empresarial (ERP)',
    'Utilize ferramentas de gestão de projetos',
    'Assegure segurança da informação',
    'Adote computação em nuvem',
    'Invista em hardware e software atualizados',
    'Padronize documentos e modelos',
    'Crie manual de procedimentos operacionais padrão',
    'Implemente metodologias ágeis',
    'Garanta qualidade consistente do produto/serviço',
    'Padronize processos de entrega do serviço',
    'Simplifique experiência do usuário (UX)',
    'Crie diferenciais competitivos claros',
    'Desenvolva versões premium ou pacotes agregados',
    'Otimize gestão de fornecedores',
    'Implemente controle de qualidade total',
    'Crie sistema de manutenção preventiva',
    'Estabeleça controle de produtividade',
    'Implemente melhorias de layout operacional',
    'Crie sistema de gestão de inventário',
    'Implemente lean manufacturing/operações',
    'Estabeleça métricas de eficiência operacional',
    'Crie plano de contingência operacional',
    'Implemente gestão visual (5S)',
    'Estabeleça padrões de qualidade',
    'Crie sistema de monitoramento de processos',
    'Implemente melhoria contínua (Kaizen)',
    'Estabeleça controle de prazos de entrega',
    'Crie sistema de rastreabilidade',
    'Desenvolva sistema de supply chain otimizado',
    'Estabeleça controle de capacity planning',
    'Implemente sistema de demand forecasting',
    'Crie programa de vendor management',
    'Desenvolva sistema de workflow automation',
    'Estabeleça controle de service level agreements',
    'Implemente sistema de resource optimization',
    'Crie programa de operational excellence',
    'Desenvolva sistema de process mining',
    'Estabeleça controle de bottleneck management',
    'Implemente sistema de load balancing',
    'Crie programa de cost reduction initiatives',
    'Desenvolva sistema de value stream mapping',
    'Estabeleça controle de cycle time reduction',
    'Implemente sistema de throughput optimization',
    'Crie programa de waste elimination',
    'Desenvolva sistema de capacity utilization',
    'Estabeleça controle de operational KPIs',
    'Implemente sistema de preventive maintenance',
    'Crie programa de equipment effectiveness',
    'Desenvolva sistema de inventory optimization',
    'Estabeleça controle de procurement processes',
    'Implemente sistema de logistics optimization',
    'Crie programa de distribution efficiency',
    'Desenvolva sistema de order fulfillment',
    'Estabeleça controle de production scheduling',
    'Implemente sistema de material requirements planning',
    'Crie programa de just-in-time operations',
    'Desenvolva sistema de total productive maintenance',
    'Estabeleça controle de statistical process control',
    'Implemente sistema de six sigma operations',
    'Crie programa de continuous improvement',
    'Desenvolva sistema de business process reengineering',
    'Estabeleça controle de operational risk management',
    'Implemente sistema de disaster recovery planning',
    'Crie programa de business continuity management',
    'Desenvolva sistema de operational dashboards',
    'Estabeleça controle de performance monitoring',
    'Implemente sistema de predictive analytics',
    'Crie programa de automation roadmap'
  ],
  tecnologia: [
    'Implemente infraestrutura de TI robusta',
    'Crie backup e segurança de dados',
    'Estabeleça conectividade adequada',
    'Implemente softwares essenciais integrados',
    'Crie política de uso de tecnologia',
    'Otimize sistemas existentes',
    'Implemente soluções em nuvem',
    'Crie automações inteligentes',
    'Estabeleça suporte técnico especializado',
    'Implemente atualizações de segurança',
    'Desenvolva soluções de analytics avançado',
    'Crie integrações entre sistemas',
    'Desenvolva soluções customizadas',
    'Estabeleça processo de inovação tecnológica',
    'Implemente ferramentas de BI (Business Intelligence)',
    'Crie sistema de monitoramento de performance',
    'Implemente chatbots e automação de atendimento',
    'Estabeleça política de LGPD e proteção de dados',
    'Crie aplicativo mobile para clientes',
    'Implemente sistema de assinatura eletrônica',
    'Desenvolva API para integrações',
    'Implemente sistema de análise de dados',
    'Crie plataforma de self-service',
    'Estabeleça governança de dados',
    'Implemente sistema de versionamento',
    'Crie documentação técnica completa',
    'Estabeleça testes automatizados',
    'Implemente monitoramento de sistemas',
    'Crie disaster recovery plan',
    'Estabeleça arquitetura escalável',
    'Desenvolva estratégia de cloud computing',
    'Implemente sistema de cybersecurity avançado',
    'Crie plataforma de machine learning',
    'Estabeleça arquitetura de microserviços',
    'Implemente sistema de containerização',
    'Desenvolva estratégia de DevOps',
    'Crie sistema de continuous integration',
    'Estabeleça processo de continuous deployment',
    'Implemente sistema de load testing',
    'Desenvolva estratégia de edge computing',
    'Crie sistema de real-time analytics',
    'Estabeleça arquitetura de data lake',
    'Implemente sistema de artificial intelligence',
    'Desenvolva estratégia de blockchain',
    'Crie sistema de Internet of Things (IoT)',
    'Estabeleça processo de agile development',
    'Implemente sistema de version control',
    'Desenvolva estratégia de mobile-first',
    'Crie sistema de progressive web apps',
    'Estabeleça arquitetura de serverless computing',
    'Implemente sistema de automated testing',
    'Desenvolva estratégia de digital transformation',
    'Crie sistema de data visualization',
    'Estabeleça processo de code review',
    'Implemente sistema de performance monitoring',
    'Desenvolva estratégia de cloud migration',
    'Crie sistema de API management',
    'Estabeleça arquitetura de event-driven systems',
    'Implemente sistema de message queuing',
    'Desenvolva estratégia de robotic process automation',
    'Crie sistema de augmented reality',
    'Estabeleça processo de technology governance',
    'Implemente sistema de zero trust security',
    'Desenvolva estratégia de quantum computing readiness',
    'Crie sistema de natural language processing',
    'Estabeleça arquitetura de headless commerce',
    'Implemente sistema de computer vision',
    'Desenvolva estratégia de 5G integration',
    'Crie sistema de predictive analytics',
    'Estabeleça processo de technology roadmapping',
    'Implemente sistema de digital twin technology'
  ],
  cultura: [
    'Defina missão, visão e valores atualizados',
    'Crie código de conduta empresarial',
    'Estabeleça comunicação clara de propósito',
    'Implemente práticas de transparência',
    'Crie ambiente de trabalho saudável',
    'Desenvolva eventos de integração da equipe',
    'Implemente práticas de feedback contínuo',
    'Crie programas de reconhecimento',
    'Estabeleça rituais organizacionais',
    'Implemente práticas de bem-estar',
    'Crie programa de embaixadores da cultura',
    'Implemente inovação organizacional',
    'Desenvolva responsabilidade social corporativa',
    'Estabeleça cultura de alta performance',
    'Promova aprendizado contínuo organizacional',
    'Crie cultura orientada a dados',
    'Fomente responsabilidade social corporativa (RSC)',
    'Promova sustentabilidade nas operações',
    'Encoraje pensamento "fora da caixa"',
    'Comunique regularmente visão de futuro da empresa',
    'Crie cultura de inovação',
    'Estabeleça valores organizacionais claros',
    'Implemente comunicação interna eficaz',
    'Crie senso de pertencimento',
    'Estabeleça cultura colaborativa',
    'Implemente gestão de mudanças',
    'Crie ambiente de confiança',
    'Estabeleça cultura de resultados',
    'Implemente diversidade e inclusão',
    'Crie tradições empresariais',
    'Desenvolva cultura de ownership mental',
    'Estabeleça rituais de celebração',
    'Implemente programa de storytelling corporativo',
    'Crie cultura de experimentação',
    'Desenvolva programa de voluntary work',
    'Estabeleça cultura de customer obsession',
    'Implemente práticas de mindfulness corporativo',
    'Crie programa de culture champions',
    'Desenvolva rituais de onboarding cultural',
    'Estabeleça cultura de continuous learning',
    'Implemente programa de culture measurement',
    'Crie sistema de culture feedback loops',
    'Desenvolva programa de cultural ambassadors',
    'Estabeleça cultura de psychological safety',
    'Implemente práticas de work-life integration',
    'Crie programa de culture evolution',
    'Desenvolva rituais de team bonding',
    'Estabeleça cultura de open communication',
    'Implemente programa de culture storytelling',
    'Crie sistema de culture metrics',
    'Desenvolva programa de culture immersion',
    'Estabeleça cultura de rapid iteration',
    'Implemente práticas de culture reinforcement',
    'Crie programa de culture documentation',
    'Desenvolva rituais de knowledge sharing',
    'Estabeleça cultura de bias awareness',
    'Implemente programa de culture coaching',
    'Crie sistema de culture dashboards',
    'Desenvolva programa de culture transformation',
    'Estabeleça cultura de environmental consciousness',
    'Implemente práticas de culture assessment',
    'Crie programa de culture alignment',
    'Desenvolva rituais de culture celebration',
    'Estabeleça cultura de social impact',
    'Implemente programa de culture evolution tracking',
    'Crie sistema de culture health monitoring',
    'Desenvolva programa de culture best practices',
    'Estabeleça cultura de global mindset',
    'Implemente práticas de culture integration',
    'Crie programa de culture legacy building'
  ],
  relacionamento: [
    'Fortaleça relacionamento com fornecedores chave',
    'Construa rede de contatos (Networking) ativa',
    'Participe de associações e câmaras de comércio',
    'Busque parceiros estratégicos para crescimento',
    'Cultive relações com influenciadores do setor',
    'Ofereça conteúdo de valor para rede de contatos',
    'Participe de grupos de discussão e fóruns online',
    'Realize eventos para clientes e parceiros',
    'Solicite indicações de clientes satisfeitos',
    'Mantenha relacionamento pós-venda ativo',
    'Crie programa de embaixadores de marca',
    'Desenvolva parcerias de co-criação',
    'Estabeleça programa de mentoring setorial',
    'Crie comunidade online de clientes',
    'Implemente programa de fidelidade avançado',
    'Desenvolva relacionamento com investidores',
    'Crie parcerias acadêmicas',
    'Estabeleça relacionamento com mídia especializada',
    'Desenvolva programa de parceiros tecnológicos',
    'Crie relacionamento com órgãos reguladores',
    'Estabeleça network de fornecedores estratégicos',
    'Crie parcerias com concorrentes (coopetição)',
    'Desenvolva relacionamento com startups',
    'Estabeleça parcerias internacionais',
    'Crie ecosystem de parceiros',
    'Desenvolva relacionamento com universidades',
    'Estabeleça parcerias com ONGs',
    'Crie network de mentores e advisors',
    'Desenvolva relacionamento com governo',
    'Estabeleça parcerias com aceleradoras',
    'Implemente programa de strategic partnerships',
    'Desenvolva sistema de partner management',
    'Crie programa de joint ventures',
    'Estabeleça network de thought leaders',
    'Implemente programa de ecosystem building',
    'Desenvolva sistema de relationship mapping',
    'Crie programa de stakeholder engagement',
    'Estabeleça network de industry experts',
    'Implemente programa de alliance management',
    'Desenvolva sistema de partnership scoring',
    'Crie programa de co-innovation partnerships',
    'Estabeleça network de angel investors',
    'Implemente programa de vendor partnerships',
    'Desenvolva sistema de relationship analytics',
    'Crie programa de cross-industry partnerships',
    'Estabeleça network de board advisors',
    'Implemente programa de channel partnerships',
    'Desenvolva sistema de partnership ROI tracking',
    'Crie programa de international partnerships',
    'Estabeleça network de industry associations',
    'Implemente programa de technology partnerships',
    'Desenvolva sistema de partner enablement',
    'Crie programa de distribution partnerships',
    'Estabeleça network de regulatory bodies',
    'Implemente programa de research partnerships',
    'Desenvolva sistema de partner communication',
    'Crie programa de supply chain partnerships',
    'Estabeleça network de customer advocates',
    'Implemente programa de marketing partnerships',
    'Desenvolva sistema de partner performance metrics',
    'Crie programa de sustainability partnerships',
    'Estabeleça network de innovation partners',
    'Implemente programa de digital partnerships',
    'Desenvolva sistema de partner lifecycle management',
    'Crie programa de platform partnerships',
    'Estabeleça network de industry influencers',
    'Implemente programa de strategic alliances',
    'Desenvolva sistema de partnership governance',
    'Crie programa de ecosystem orchestration',
    'Estabeleça network de global partners'
  ],
  produto: [
    'Inove continuamente no produto/serviço',
    'Escute ativamente feedback do cliente',
    'Realize testes A/B em ofertas e páginas',
    'Invista em P&D (Pesquisa e Desenvolvimento)',
    'Ofereça suporte ao cliente excepcional',
    'Realize pesquisas de necessidades do cliente',
    'Priorize desenvolvimento baseado no impacto (ROI)',
    'Implemente ciclos de desenvolvimento ágeis',
    'Teste novas funcionalidades com grupos beta',
    'Realize testes de usabilidade (User Testing)',
    'Monitore métricas de uso do produto',
    'Desenvolva roadmaps de produto claros',
    'Garanta escalabilidade da infraestrutura',
    'Implemente gerenciamento de bugs e melhorias',
    'Foque em diferencial competitivo único (USP)',
    'Crie versões simplificadas (MVP)',
    'Integre produto com outras ferramentas/sistemas',
    'Desenvolva tutoriais em vídeo e guias de uso',
    'Realize análises de mercado para novas oportunidades',
    'Conduza análises de concorrência de produto',
    'Implemente analytics de produto',
    'Crie programa de beta testers',
    'Estabeleça métricas de sucesso do produto',
    'Implemente design thinking',
    'Crie user personas detalhadas',
    'Estabeleça processo de ideação',
    'Implemente prototipagem rápida',
    'Crie backlog de funcionalidades',
    'Estabeleça critérios de aceitação',
    'Implemente testes de performance',
    'Desenvolva estratégia de product-market fit',
    'Crie sistema de user journey mapping',
    'Estabeleça processo de feature prioritization',
    'Implemente metodologia lean startup',
    'Desenvolva sistema de product analytics',
    'Crie programa de user research',
    'Estabeleça processo de competitive analysis',
    'Implemente sistema de product telemetry',
    'Desenvolva estratégia de product positioning',
    'Crie sistema de user feedback loops',
    'Estabeleça processo de concept validation',
    'Implemente metodologia jobs-to-be-done',
    'Desenvolva sistema de product metrics dashboard',
    'Crie programa de customer development',
    'Estabeleça processo de market research',
    'Implemente sistema de product lifecycle management',
    'Desenvolva estratégia de product differentiation',
    'Crie sistema de user experience optimization',
    'Estabeleça processo de value proposition design',
    'Implemente metodologia design sprint',
    'Desenvolva sistema de product discovery',
    'Crie programa de product evangelism',
    'Estabeleça processo de technical debt management',
    'Implemente sistema de product quality assurance',
    'Desenvolva estratégia de product scalability',
    'Crie sistema de user onboarding optimization',
    'Estabeleça processo de product vision alignment',
    'Implemente metodologia outcome-driven innovation',
    'Desenvolva sistema de product growth metrics',
    'Crie programa de product community building',
    'Estabeleça processo de feature adoption tracking',
    'Implemente sistema de product experimentation',
    'Desenvolva estratégia de product ecosystem',
    'Crie sistema de user retention optimization',
    'Estabeleça processo de product marketing alignment',
    'Implemente metodologia product-led growth',
    'Desenvolva sistema de product intelligence',
    'Crie programa de product advocacy',
    'Estabeleça processo de product roadmap communication',
    'Implemente sistema de product health monitoring'
  ],
  "sucesso-cliente": [
    'Mapeie jornada do cliente pós-venda',
    'Implemente processo de onboarding robusto',
    'Realize pesquisas de satisfação (CSAT, NPS, CES)',
    'Crie programa de acompanhamento proativo',
    'Designe gerentes de sucesso do cliente dedicados',
    'Ofereça canais de suporte múltiplos e eficientes',
    'Desenvolva base de conhecimento para autoatendimento',
    'Implemente sistema de gestão de tickets/chamados',
    'Personalize comunicação de pós-venda',
    'Crie programa de fidelidade para clientes leais',
    'Realize webinars exclusivos para clientes',
    'Monitore churn rate e identifique causas raiz',
    'Desenvolva estratégias de reengajamento',
    'Crie canal exclusivo para clientes VIP',
    'Promova encontros ou comunidades online',
    'Colete feedback contínuo para melhorias',
    'Ofereça consultorias personalizadas',
    'Antecipe necessidades futuras dos clientes',
    'Desenvolva plano de recuperação para insatisfeitos',
    'Implemente programa de upsell e cross-sell ético',
    'Crie health score para clientes',
    'Estabeleça métricas de sucesso do cliente',
    'Implemente early warning system',
    'Crie programa de advocacy',
    'Estabeleça touchpoints regulares',
    'Implemente customer journey mapping',
    'Crie programa de educação do cliente',
    'Estabeleça SLA de atendimento',
    'Implemente voice of customer program',
    'Crie centro de excelência em customer success',
    'Desenvolva estratégia de customer lifetime value',
    'Implemente sistema de customer segmentation',
    'Crie programa de customer expansion',
    'Estabeleça processo de renewal optimization',
    'Implemente sistema de customer risk assessment',
    'Desenvolva estratégia de customer engagement',
    'Crie programa de customer training',
    'Estabeleça processo de escalation management',
    'Implemente sistema de customer feedback analytics',
    'Desenvolva estratégia de customer retention',
    'Crie programa de customer co-creation',
    'Estabeleça processo de customer success playbooks',
    'Implemente sistema de customer behavior tracking',
    'Desenvolva estratégia de customer experience design',
    'Crie programa de customer advisory board',
    'Estabeleça processo de customer success automation',
    'Implemente sistema de customer sentiment analysis',
    'Desenvolva estratégia de customer-centric culture',
    'Crie programa de customer success metrics',
    'Estabeleça processo de customer success coaching',
    'Implemente sistema de customer success technology stack',
    'Desenvolva estratégia de customer success scaling',
    'Crie programa de customer success certification',
    'Estabeleça processo de customer success governance',
    'Implemente sistema de customer success intelligence',
    'Desenvolva estratégia de customer success innovation',
    'Crie programa de customer success best practices',
    'Estabeleça processo de customer success transformation',
    'Implemente sistema de customer success performance',
    'Desenvolva estratégia de customer success excellence',
    'Crie programa de customer success leadership',
    'Estabeleça processo de customer success evolution',
    'Implemente sistema de customer success optimization',
    'Desenvolva estratégia de customer success mastery',
    'Crie programa de customer success revolution',
    'Estabeleça processo de customer success sustainability',
    'Implemente sistema de customer success breakthrough',
    'Desenvolva estratégia de customer success transformation',
    'Crie programa de customer success acceleration'
  ]
};
