
export const METRIC_TITLES: { [key: string]: string } = {
  'showTicketFaturamento': 'Ticket Faturamento',
  'showTicketReceita': 'Ticket Receita',
  'showFaltaFaturamento': 'Falta de Faturamento',
  'showFaltaReceita': 'Falta de Receita',
  'showDiariaReceita': 'Diária de Receita',
  'showDiariaFaturamento': 'Diária de Faturamento',
  'showSuperMetaFaturamento': 'Super Meta Faturamento',
  'showSuperMetaReceita': 'Super Meta Receita',
  'showHiperMetaFaturamento': 'Hiper Meta Faturamento',
  'showHiperMetaReceita': 'Hiper Meta Receita',
  'showFaltaReceitaSuper': 'Falta Receita (Super)',
  'showFaltaReceitaHiper': 'Falta Receita (Hiper)',
  'showFaltaFaturamentoSuper': 'Falta Faturamento (Super)',
  'showFaltaFaturamentoHiper': 'Falta Faturamento (Hiper)',
  'showMetaFaturamento': 'Meta Faturamento',
  'showMetaReceita': 'Meta Receita',
  'showFaturamento': 'Faturamento',
  'showReceita': 'Receita',
  'showQuantidadeVendas': 'Quantidade de Vendas',
  'showCashCollect': 'Cash Collect',
  'showCac': 'CAC (Custo de Aquisição)',
  'showConversion': 'Taxa de Conversão',
  'showRevenue': 'Receita',
  'showProjecaoReceita': 'Projeção de Receita',
  'showProjecaoFaturamento': 'Projeção de Faturamento',
  'showNoShow': 'No-Show',
  'showClosersPerformanceTable': 'Tabela de desempenho dos closers',
  'specificGoals': 'Metas Específicas',
  'revenueEvolutionChart': 'Gráfico de Evolução de Receita',
  'billingEvolutionChart': 'Gráfico de Evolução de Faturamento',
  'sellerRevenueChart': 'Gráfico de Receita por Vendedor',
  'sellerBillingChart': 'Gráfico de Faturamento por Vendedor',
  'temporalRevenueChart': 'Gráfico de Análise Temporal de Receita',
  'temporalBillingChart': 'Gráfico de Análise Temporal de Faturamento',
  'closersPerformanceTable': 'Tabela de desempenho dos closers'
};

export const ALL_METRIC_KEYS = [
  'showConversion', 'showRevenue',
  'showTicketFaturamento', 'showTicketReceita', 'showFaltaFaturamento', 
  'showFaltaReceita', 'showDiariaReceita', 'showDiariaFaturamento',
  'showSuperMetaFaturamento', 'showSuperMetaReceita', 'showHiperMetaFaturamento',
  'showHiperMetaReceita', 'showFaltaReceitaSuper',
  'showFaltaReceitaHiper', 'showFaltaFaturamentoSuper', 'showFaltaFaturamentoHiper',
  'showMetaFaturamento', 'showMetaReceita', 'showFaturamento', 'showReceita', 
  'showQuantidadeVendas', 'showCashCollect', 'showCac',
  'showProjecaoReceita', 'showProjecaoFaturamento', 'showNoShow',
  'showClosersPerformanceTable'
];
