
export const PRODUCT_METRICS_LABELS: Record<string, string> = {
  showProductReceita: 'Receita do Produto',
  showProductFaturamento: 'Faturamento do Produto',
  showProductQuantidadeVendas: 'Quantidade de Vendas do Produto',
  showProductTicketReceita: 'Ticket Receita do Produto',
  showProductTicketFaturamento: 'Ticket Faturamento do Produto',
  showProductMetaReceita: 'Meta Receita do Produto',
  showProductMetaFaturamento: 'Meta Faturamento do Produto',
  showProductMetaQuantidadeVendas: 'Meta Quantidade de Vendas do Produto',
  showProductFaltaReceita: 'Falta de Receita do Produto',
  showProductFaltaFaturamento: 'Falta de Faturamento do Produto',
  showProductCashCollect: 'Cash Collect do Produto',
  showProductProjecaoReceita: 'Projeção de Receita do Produto',
  showProductProjecaoFaturamento: 'Projeção de Faturamento do Produto',
  showProductRevenueEvolutionChart: 'Gráfico de Evolução de Receita por Produto',
  showProductBillingEvolutionChart: 'Gráfico de Evolução de Faturamento por Produto',
  showProductSalesEvolutionChart: 'Gráfico de Evolução de Vendas por Produto',
  showProductPerformanceChart: 'Gráfico de Performance dos Produtos',
  showProductComparisonChart: 'Gráfico de Comparação entre Produtos',
  showProductTemporalChart: 'Gráfico de Análise Temporal dos Produtos',
};
